#!/bin/sh
RIDER_FOLDER="Rider2021.3"
RIDER_PREFS_PATH="$HOME/Library/Application Support/JetBrains/$RIDER_FOLDER"
COLORS_FOLDER="colors"
KEYMAPS_FOLDER="keymaps"
cp "./$COLORS_FOLDER"/* "$RIDER_PREFS_PATH/$COLORS_FOLDER"  
cp "./$KEYMAPS_FOLDER"/* "$RIDER_PREFS_PATH/$KEYMAPS_FOLDER"  